{
 "title": "ArangoDB monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Aggregate_Interval", "query": "1m,5m,15m,30m,1h,6h" }
  ]
 },
 "panels": [
  { "title": "Generic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Total Uptime from last restart",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "arangodb_server_statistics_server_uptime"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "description": "Active connections",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "arangodb_client_connection_statistics_client_connections"
    }
   ]
  },
  {
   "title": "Active threads",
   "type": "stat",
   "description": "Active thread count",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "arangodb_process_statistics_number_of_threads"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total memory",
   "type": "stat",
   "description": "Total DB memory",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "arangodb_server_statistics_physical_memory"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "description": "Total memory used percentage",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "arangodb_process_statistics_resident_set_size_percent",
     "legendFormat": "Memory used %"
    }
   ]
  },
  {
   "title": "Swap memory",
   "type": "stat",
   "description": "Virtual memory available for arango process",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "arangodb_process_statistics_virtual_memory_size"
    }
   ]
  },
  { "title": "Live Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(arangodb_client_connection_statistics_bytes_received_sum[$Aggregate_Interval])",
     "legendFormat": "Bytes Received"
    },
    {
     "expr": "increase(arangodb_client_connection_statistics_bytes_sent_sum[$Aggregate_Interval])",
     "legendFormat": "Bytes Sent"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "description": "Number of POST requests aggregated over selected aggregate time interval.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(arangodb_http_request_statistics_http_post_requests{instance=\"15.1.134.30:9101\"}[$Aggregate_Interval])",
     "legendFormat": "POST requests"
    },
    {
     "expr": "increase(arangodb_http_request_statistics_http_get_requests{instance=\"15.1.134.30:9101\"}[$Aggregate_Interval])",
     "legendFormat": "GET requests"
    },
    {
     "expr": "increase(arangodb_http_request_statistics_http_put_requests{instance=\"15.1.134.30:9101\"}[$Aggregate_Interval])",
     "legendFormat": "PUT requests"
    },
    {
     "expr": "increase(arangodb_http_request_statistics_http_delete_requests{instance=\"15.1.134.30:9101\"}[$Aggregate_Interval])",
     "legendFormat": "DELETE requests"
    }
   ]
  },
  {
   "title": "Queued queries",
   "type": "graph",
   "description": "Total number of queries queued for processing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(arangodb_scheduler_queue_length[$Aggregate_Interval])"
    }
   ]
  },
  {
   "title": "Aborted transactions",
   "type": "graph",
   "description": "Total number of transactions aborted over the aggregated time interval.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(arangodb_transactions_aborted[$Aggregate_Interval])"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(arangodb_client_connection_statistics_request_time_sum[$Aggregate_Interval])/increase(arangodb_http_request_statistics_total_requests[$Aggregate_Interval])",
     "legendFormat": "Avg request time"
    }
   ]
  }
 ]
}